version: '3.8'

services:
  nginx-projextpal:
    image: nginx:alpine
    container_name: projextpal-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-projextpal.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - projextpal_projextpal-network
    restart: unless-stopped

networks:
  projextpal_projextpal-network:
    external: true
